# Publishes artifacts for testing...
trigger: none
pr: none

pool: Default
# pool:
#  vmImage: windows-latest

# pool:
#   vmImage: win1803

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: 'mkdir Source/Timely.Main/bin/emptyDir'

# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: 'mkdir EmptyDirectory'

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: ''
#     ArtifactName: 'Release'
#     SilentCopy: true

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: 'Source/Timely.Main/bin/Release'
#     ArtifactName: 'Vienna'

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '
#     ArtifactName: 'Tokyo'
#     publishLocation: 'FilePath'
#     TargetPath: 'C:\Users\jogros\filePathArtifact'
#     Parallel: true
#     ParallelCount: 4

- script: |
    echo '##vso[task.setvariable variable=localFileShare'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $ArtifactDir = $env:BUILD_ARTIFACTSTAGINGDIRECTORY
      $ArtifactDir = "\\localhost\$ArtifactDir.Replace(":", "$")"
      echo $ArtifactDir
      echo '##vso[task.setvariable variable=LocalFileShare]$ArtifactDir'

- task: PublishBuildArtifacts@1
  displayName: "PBA No Options"
  inputs:
    PathtoPublish: 'Source/Timely.Main/bin/Release'
    ArtifactName: 'drop'
    publishLocation: 'FilePath'
    TargetPath: '$(LocalFileShare)'

# - task: PublishBuildArtifacts@1
#   displayName: "PBA All Options"
#   inputs:
#     PathtoPublish: 'Source/Timely.Main/bin/Release'
#     ArtifactName: 'drop'
#     publishLocation: 'FilePath'
#     TargetPath: '\\localhost\c$\users\jogros\'
#     Parallel: true
#     FileCopyOptions: '/NDL /NFL'

# - task: PublishBuildArtifacts@1
#   displayName: "PBA Parallel Only"
#   inputs:
#     PathtoPublish: 'Source/Timely.Main/bin/Release'
#     ArtifactName: 'drop'
#     publishLocation: 'FilePath'
#     TargetPath: '\\localhost\c$\users\jogros\'
#     Parallel: true

# - task: PublishBuildArtifacts@1
#   displayName: "PBA File Copy Options Only 1"
#   inputs:
#     PathtoPublish: 'Source/Timely.Main/bin/Release'
#     ArtifactName: 'drop'
#     publishLocation: 'FilePath'
#     TargetPath: '\\localhost\c$\users\jogros\'
#     Parallel: true
#     FileCopyOptions: '/NFL'

# - task: PublishBuildArtifacts@1
#   displayName: "PBA File Copy Options Only 2"
#   inputs:
#     PathtoPublish: 'Source/Timely.Main/bin/Release'
#     ArtifactName: 'drop'
#     publishLocation: 'FilePath'
#     TargetPath: '\\localhost\c$\users\jogros\'
#     FileCopyOptions: '/NDL /NFL'

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: 'Source/Timely.Main/bin/Release'
#     ArtifactName: 'London'
#     publishLocation: FilePath
#     TargetPath: Source/Timely.Main/publish

# - task: PublishPipelineArtifact@0
#   inputs:
#     artifactName: 'Tokyo'
#     targetPath: 'Source/Timely.Main/bin/'

# - task: PublishPipelineArtifact@0
#   inputs:
#     artifactName: 'empty-directory'
#     targetPath: 'EmptyDirectory'
