# Publishes artifacts for testing...

trigger: none
pr: none

# pool: Default
pool:
 vmImage: windows-latest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: 'mkdir Source/Timely.Main/bin/emptyDir'

# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: 'mkdir EmptyDirectory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Source/Timely.Main/bin/Release'
    ArtifactName: 'release'

# - task: PublishPipelineArtifact@0
#   inputs:
#     artifactName: 'executable-pipelines'
#     targetPath: 'Source/Timely.Main/bin/'

# - task: PublishPipelineArtifact@0
#   inputs:
#     artifactName: 'empty-directory'
#     targetPath: 'EmptyDirectory'