# Publishes artifacts for testing...

trigger:
- master

# pool: Default
pool:
  vmImage: windows-latest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Source/Timely.Main/bin/'
    ArtifactName: 'executable'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'executable-pipelines'
    targetPath: 'Source/Timely.Main/bin/'

#- upload: 'Source/Timely.Main/bin/Release/Timely.Main.exe'
